@david_admin_jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Njg2MzMzMDR9.39k3GQC2mPcvLYl-SoVhpRHXCqyUnxAHiHbX3mxSeEg

@tina-jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2Njg3ODY0NTF9.xqDjMXALeP3GJI8VibBcpYHVS44L8bI2QWEgZdiRjyc

### PRODUCTS INDEX

GET http://localhost:3000/products.json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjgxOTUxOTF9.F6azKxum9SHG49Mfid5BJeGGrWA8Io10hV-nI9M8tDo

### PRODUCTS SHOW

GET http://localhost:3000/products/5.json

### PRODUCTS CREATE

POST http://localhost:3000/products.json
Content-Type: application/json
Authorization: Bearer {{david_admin_jwt}}

{
  "name": "Nintendo Switch",
  "price": 299.99, 
  "description": "The Nintendo Switch. What else do I need to say?",
  "supplier_id": 1
}

### PRODUCTS UPDATE

PATCH http://localhost:3000/products/33.json
Authorization: Bearer {{tina-jwt}}
Content-Type: application/json

{
  "name": "DID THIS WORK?"
}

### PRODUCTS DELETE

DELETE http://localhost:3000/products/33.json
Authorization: Bearer {{tina-jwt}}
Content-Type: application/json


### USERS CREATE

POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Tina Weymouth",
  "email": "tinaweymouth@gmail.com",
  "password": "ih8david",
  "password_confirmation": "ih8davi"
}

### USERS INDEX

GET http://localhost:3000/users.json


### SESSIONS CREATE

POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "tinaweymouth@example.com",
  "password": "ih8david"
}


### PRODUCTS CREATE

POST http://localhost:3000/products.json
Authorization: Bearer {{tina-jwt}}
Content-Type: application/json


{
  "name": "Nintendo Switch",
  "price": 299.99, 
  "description": "The Nintendo Switch. What else do I need to say?",
  "supplier_id": 1
}

### ORDER CREATE

POST http://localhost:3000/orders.json
Content-Type: application/json
Authorization: Bearer {{tina-jwt}}

{
  "user_id": 1,
  "product_id": 5,
  "quantity": 1
}

### ORDERS SHOW

GET http://localhost:3000/orders/9.json
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NjgyODM3NTB9.51JySQCxL_2fBGg8P4Yuvz4QFKQW6888108Uz57fzWM

### ORDERS INDEX

GET http://localhost:3000/orders.json
Content-Type: application/json
Authorization: Bearer 

### CARTPRODUCTS CREATE

POST http://localhost:3000/cart.json
Content-Type: application/json
Authorization: Bearer {{tina-jwt}}

{
  "user_id": 2,
  "product_id": 5,
  "quantity": 1,
  "status": "removed",
  "order_id": 1

}

### CARTPRODUCTS INDEX

GET http://localhost:3000/cart.json
Content-Type: application/json
Authorization: Bearer {{tina-jwt}}

### CARTPRODUCTS DELETE

DELETE http://localhost:3000/cart/6.json
Content-Type: application/json
Authorization: Bearer {{tina-jwt}}

